Repository vishal02527/My-Strength-Shree-Krishna, pull requests merged in 2024-10, with the labels that each got.

#142 adding animation effect to social media icons
  devotional-resources.html
  gallery.html
  index.html
  scriptures.html
Labels: label1

#228 Change in CSS of class krishna-image
  index.html
Labels: level1

#213 Styled the scroll to top button with arrow up icon
  devotional-resources.html
  dhanna-jatt.html
  discussion-forum.html
  divine-wallpapers.html
  gallery.html
  index.html
  karmati-bai.html
  meera-bai.html
  morning-mantra-audio.html
  narsi.html
  raidas.html
  scriptures.html
  stories-of-devotees.html
  surdas.html
  taj-biwi.html
Labels: gssoc-ext, level1

#218 Add Mini chatbot
  boy.png
  chatbot.html
  index.html
  panditji.png
Labels: gssoc-ext, level3

#327 Added detailed learning html pages for Srimad Bhagavatam, Bhagavad Gita & Mahabharat
  bhagavad_gita_details.html
  mahabharata_details.html
  scriptures.html
  srimad_bhagavatam_details.html
Labels: gssoc-ext, level2

#403 Stylised the signup and login.html page
  login.html
  signup.html
Labels: gssoc-ext, level2

#431 Aligned the input field centerly
  login.html
  signup.html
Labels: gssoc-ext, level1

#500 Enhanced names in the gallery section
  gallery.html
  index.html
Labels: level1

#461 Added dark mode functionality to entire website
  Feedback.html
  Personalized.html
  avatars.css
  avatars.html
  bhagavad_gita_details.html
  chatbot.html
  devotional-resources.html
  dhanna-jatt.html
  discussion-forum.html
  divine-wallpapers.html
  gallery.html
  images/moon.png
  images/sun.png
  index.html
  karmati-bai.html
  login.html
  mahabharata_details.html
  meera-bai.html
  morning-mantra-audio.html
  narsi.html
  partner.html
  quiz.html
  raidas.html
  script.js
  scriptures.html
  signup.html
  srimad_bhagavatam_details.html
  stories-of-devotees.html
  surdas.html
  taj-biwi.html
Labels: gssoc-ext, level2

#592 Change in class krishna-image
  index.html
Labels: gssoc-ext

#612 Improve contrast for quiz box in dark mode
  quiz.html
Labels: gssoc-ext, level1

#664 remove bullet points from our collabrator section of the page.add more content the the page like upcoming events and galley section . this helps to make the page more engaging. and improve the overall layout
  partner.html
Labels: gssoc-ext, level1
