Repository vishal02527/My-Strength-Shree-Krishna, pull requests merged in 2024-11, with the labels that each got.

#739 Pop up Dialogue box added to to every Recipe card.
  prasadam.css
  prasadam.html
  prasadam.js
Labels: gssoc-ext, level3

#746 Make translate to hindi button on avatars page done ! #726 #741
  avatars.css
  avatars.html
Labels: gssoc-ext, level2

#761 Fixing 757 #issue
  images/event1.jpg
  images/event2.jpg
  partner.html
Labels: gssoc-ext, level1
